[project]
name = "llm-ocr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "boto3>=1.37.33",
    "loguru>=0.7.3",
]

[dependency-groups]
dev = [
    "boto3-stubs[full]>=1.37.33",
    "moto>=5.1.3",
]
